### ISSUE TITLE
学长好，想咨询一下这个问题

### ISSUE THREAD

**Issue by cancelGuMu** [ChenfaZheng/BNUPublicElectiveCourseMonitor#1]
![QQ浏览器截图20230618013105](https://github.com/ChenfaZheng/BNUPublicElectiveCourseMonitor/assets/120471358/91a6c1ef-0170-43cf-9ae0-c97e85fb7f48)
##提问
请问这个原理是什么，代码都可以看明白，但是不知道具体的逻辑，为什么要写循环遍历所有的行，如果学长有看到拜托学长向我的QQ邮箱3492160186@qq.com发邮件，这真的很重要！拜托了！

**Comment by ChenfaZheng** [comment]
已发邮件
